# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ImageListPOC' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ImageListPOC
  pod 'SnapKit', '~> 4.0.0'
  pod 'Alamofire'
  pod 'SDWebImage', '~> 4.0'
  pod 'SwiftLint'
  
  target 'ImageListPOCTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
